alertmanager:
  alertmanagerSpec:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 32Mi
  enabled: true
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'namespace']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      receiver: discord
      routes:
      - matchers:
        - alertname = Watchdog
        receiver: blackhole
    receivers:
    - name: blackhole
    - name: discord
      discord_configs:
      - webhook_url: 
        title: '{{ if eq .Status "firing" }}🔴{{ else }}✅{{ end }} {{ .CommonLabels.alertname }}'
        message: |
          {{ range .Alerts }}
          **Namespace:** {{ .Labels.namespace }}
          **Summary:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          {{ end }}
    inhibit_rules:
    - source_matchers:
      - severity = critical
      target_matchers:
      - severity = warning
      equal: ['alertname', 'namespace']
grafana:
  adminPassword: ringcatch-grafana
  enabled: true
  grafana.ini:
    server:
      root_url: '%(protocol)s://%(domain)s/grafana'
  persistence:
    enabled: true
    size: 2Gi
  service:
    type: ClusterIP
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
kubeProxy:
  enabled: false
kubeScheduler:
  enabled: false
kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: true
prometheus:
  prometheusSpec:
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 512Mi
    retention: 7d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
